# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f935d4e94f7cb497bb0c7b8e996022a0"
name = "ShipSense"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
